### ISSUE TITLE
`lines` parameter is off by 1 when file ends with a `\n`

### ISSUE THREAD

**Issue by anson-vandoren** [mantrala/log-api#4]
It's typical for each log line (including the final line in a given file) to be appended with a newline character, however this service returns the incorrect number of lines in that case:

```
$ cat test
Line 1
Line 2
Line 3
# note, each of the above lines ends with `\n`
$ curl "localhost:4567/api/v1/logs?filename=test.log&lines=1"
{
    "data": [

    ]
}
$curl "localhost:4567/api/v1/logs?filename=test.log&lines=2"
{
    "data": [
        "Line 3"
    ]
}
```

I would expect the first to have returned Line 3, and the second to have returned both Line 3 and Line 2

**Comment by mantrala** [comment]
done!
